# All available Hugo versions are listed here:
# https://gitlab.com/pages/hugo/container_registry
image: registry.gitlab.com/pages/hugo/hugo_extended:0.101.0

build_deploy:
  only:
    - master
  variables:
    # Set to "true" for lots of info in the logs
    CI_DEBUG_TRACE: "false"
  before_script:
    - cat /etc/os-release
    - apk update
    - apk add openssh-client rsync
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_HOST_KEY" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - hugo --gc --minify
    - |
      rsync --verbose --recursive --times --delete --progress --human-readable \
      -e 'ssh -p "'"$SSH_PORT"'"' \
      public/ \
      $SSH_USER@$SSH_HOST_IP:$SSH_TARGET_DIR      
